edit device load script

diff --git a/aesd-char-driver/aesdchar_load b/aesd-char-driver/aesdchar_load
--- a/aesd-char-driver/aesdchar_load
+++ b/aesd-char-driver/aesdchar_load
@@ -1,9 +1,9 @@
 #!/bin/sh
-module=aesdchar
-device=aesdchar
+module="aesdchar"
+device="aesdchar"
 mode="664"
-cd `dirname $0`
-set -e
+kernel_ver="$(uname -r)"
+
 # Group: since distributions do it differently, look for wheel or use staff
 if grep -q '^staff:' /etc/group; then
     group="staff"
@@ -11,15 +11,16 @@ else
     group="wheel"
 fi
 
-if [ -e ${module}.ko ]; then
-    echo "Loading local built file ${module}.ko"
-    insmod ./$module.ko $* || exit 1
+if [ -e /lib/modules/$kernel_ver/extra/$module.ko ]; then
+    echo "Loading /lib/modules/$kernel_ver/extra/$module.ko"
+    insmod /lib/modules/$kernel_ver/extra/$module.ko $* || exit 1
 else
-    echo "Local file ${module}.ko not found, attempting to modprobe"
-    modprobe ${module} || exit 1
+    echo "Module not found in /lib/modules/$kernel_ver/extra/, attempting modprobe"
+    modprobe $module || exit 1
 fi
+
 major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
 rm -f /dev/${device}
 mknod /dev/${device} c $major 0
 chgrp $group /dev/${device}
-chmod $mode  /dev/${device}
+chmod $mode /dev/${device}
